# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2024bf46d3140ba79cfd6497809baeaf1c6f85560cde89951b9219f7fd21b43a8d9bc4ffce81e832cbec7d08e9e72cb4df571df13a8a6cd2f676949c0c9b9df

test:
  secret_key_base: bb072600096b809fad33c2c3d959164bd2edaf3194b74520f09cdeb116aa20edb30f377e1667b23e8bceba6ccb3d00e1212e3df0b4af3f4e6bc5e6d847037146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
